language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
after_script:
#Create dist folder
- grunt build
- npm install heroku
- git remote add heroku git@heroku.com:starscream-bootstrap.git
- export HEROKU_API_KEY=ENTER_KEY_HERE
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
deploy:
  provider: heroku
  api_key:
    secure: v2rkUbehJDgWWPYRS4LMEhseSxwvorp+OqSwylv5rK97+MFBQa2mWidRqkze6kI8WdrFdDcaN/7XKYSVi2yqyNWZVq8KasRVdc3GAAzL1Epn6vCYPJq7NpA1TySnFZrEOlximc3lYRWl70r94T18AjdWqXM6A1FOZss1ro1fLW8=
  app: starscream-bootstrap
  on:
    repo: rsiwady29/starscream-bootstrap
